spring:
  h2:
    console:
      enabled: true
      path: /memo

  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://61.111.18.166:5432/memo
      username: memo
      password: memo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true