spring:
  h2:
    console:
      enabled: true
      path: /memo

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:memo;MODE=PostgreSQL;
      username: memo
      password: memo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true