-- 메모 테이블 정의
create table if not exists memos (
   id bigint generated by default as identity,
   content text not null,
   checked boolean not null,
   create_at timestamp,
   update_at timestamp,
   deleted boolean not null,
   primary key (id)
)